name: CI Tests

on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependences
        run: yarn install --frozen-lockfile

      - name: Run Unit Test
        run: yarn test
